In [1]:
import pandas as pd
import numpy as np

In [2]:
path ='bangalore house price prediction OHE-data (1).csv' 
df = pd.read_csv(path)

In [3]:
df.head()

bath  balcony  price  total_sqft_int  bhk  price_per_sqft  \
0   3.0      2.0  150.0          1672.0    3     8971.291866   
1   3.0      3.0  149.0          1750.0    3     8514.285714   
2   3.0      2.0  150.0          1750.0    3     8571.428571   
3   2.0      2.0   40.0          1250.0    2     3200.000000   
4   2.0      2.0   83.0          1200.0    2     6916.666667   

   area_typeSuper built-up  Area  area_typeBuilt-up  Area  \
0                              1                        0   
1                              0                        1   
2                              1                        0   
3                              1                        0   
4                              0                        0   

   area_typePlot  Area  availability_Ready To Move  ...  \
0                    0                           1  ...   
1                    0                           1  ...   
2                    0                           1  ...   
3                    0                           1  ...   
4                    1                           1  ...   

   location_Kalena Agrahara  location_Horamavu Agara  location_Vidyaranyapura  \
0                         0                        0                        0   
1                         0                        0                        0   
2                         0                        0                        0   
3                         0                        0                        0   
4                         0                        0                        0   

   location_BTM 2nd Stage  location_Hebbal Kempapura  location_Hosur Road  \
0                       0                          0                    0   
1                       0                          0                    0   
2                       0                          0                    0   
3                       0                          0                    0   
4                       0                          0                    0   

   location_Horamavu Banaswadi  location_Domlur  location_Mahadevpura  \
0                            0                0                     0   
1                            0                0                     0   
2                            0                0                     0   
3                            0                0                     0   
4                            0                0                     0   

   location_Tumkur Road  
0                     0  
1                     0  
2                     0  
3                     0  
4                     0  

[5 rows x 108 columns]

In [7]:
df.shape

(7120, 108)

In [8]:
X = df.drop('price',axis=1)
y = df['price']
print('X shape is',X.shape)
print('X shape is',y.shape)

X shape is (7120, 107)
X shape is (7120,)


In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=51)

print('Shape of X_train = ', X_train.shape)
print('Shape of y_train = ', y_train.shape)
print('Shape of X_test = ', X_test.shape)
print('Shape of y_test = ', y_test.shape)

Shape of X_train =  (5696, 107)
Shape of y_train =  (5696,)
Shape of X_test =  (1424, 107)
Shape of y_test =  (1424,)


In [25]:
from sklearn.neighbors import KNeighborsRegressor

In [26]:
regressor = KNeighborsRegressor(n_neighbors=5)
regressor.fit(X_train, y_train)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
                    metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                    weights='uniform')

In [27]:
regressor.score(X_test,y_test)

0.8858213777326956

In [31]:
X_test.iloc[-1,:]

bath                               2.000000
balcony                            0.000000
total_sqft_int                  1566.000000
bhk                                2.000000
price_per_sqft                 11494.252874
                                   ...     
location_Hosur Road                0.000000
location_Horamavu Banaswadi        0.000000
location_Domlur                    0.000000
location_Mahadevpura               0.000000
location_Tumkur Road               0.000000
Name: 43, Length: 107, dtype: float64

In [29]:
X_test.tail()

bath  balcony  total_sqft_int  bhk  price_per_sqft  \
2078   2.0      1.0          1090.0    2     2600.000000   
6855   3.0      1.0          1585.0    3     5299.684543   
4381   1.0      2.0           665.0    1     4812.030075   
3862   2.0      1.0          1167.0    2     5398.457584   
43     2.0      0.0          1566.0    2    11494.252874   

      area_typeSuper built-up  Area  area_typeBuilt-up  Area  \
2078                              0                        1   
6855                              1                        0   
4381                              1                        0   
3862                              1                        0   
43                                0                        0   

      area_typePlot  Area  availability_Ready To Move  location_Whitefield  \
2078                    0                           0                    0   
6855                    0                           1                    1   
4381                    0                           1                    0   
3862                    0                           0                    0   
43                      1                           1                    0   

      ...  location_Kalena Agrahara  location_Horamavu Agara  \
2078  ...                         0                        0   
6855  ...                         0                        0   
4381  ...                         0                        0   
3862  ...                         0                        0   
43    ...                         0                        0   

      location_Vidyaranyapura  location_BTM 2nd Stage  \
2078                        0                       0   
6855                        0                       0   
4381                        0                       0   
3862                        0                       0   
43                          0                       0   

      location_Hebbal Kempapura  location_Hosur Road  \
2078                          0                    0   
6855                          0                    0   
4381                          0                    0   
3862                          0                    0   
43                            0                    0   

      location_Horamavu Banaswadi  location_Domlur  location_Mahadevpura  \
2078                            0                0                     0   
6855                            0                0                     0   
4381                            0                0                     0   
3862                            0                0                     0   
43                              0                0                     0   

      location_Tumkur Road  
2078                     0  
6855                     0  
4381                     0  
3862                     0  
43                       0  

[5 rows x 107 columns]

In [33]:
regressor.predict([X_test.iloc[-1,:])

SyntaxError: invalid syntax (<ipython-input-33-f56a9cc81f9b>, line 1)

In [38]:
regressor.predict([X_test.iloc[-1, :]])

array([184.4])

In [39]:
y_test.tail()

2078     28.34
6855     84.00
4381     32.00
3862     63.00
43      180.00
Name: price, dtype: float64

In [40]:
y_test.iloc[-1]

180.0

In [43]:
regressor.predict([X_test.iloc[-2,:]])

array([63.])

In [44]:
y_test.iloc[-2]

63.0

In [50]:
X_test.tail()

bath  balcony  total_sqft_int  bhk  price_per_sqft  \
2078   2.0      1.0          1090.0    2     2600.000000   
6855   3.0      1.0          1585.0    3     5299.684543   
4381   1.0      2.0           665.0    1     4812.030075   
3862   2.0      1.0          1167.0    2     5398.457584   
43     2.0      0.0          1566.0    2    11494.252874   

      area_typeSuper built-up  Area  area_typeBuilt-up  Area  \
2078                              0                        1   
6855                              1                        0   
4381                              1                        0   
3862                              1                        0   
43                                0                        0   

      area_typePlot  Area  availability_Ready To Move  location_Whitefield  \
2078                    0                           0                    0   
6855                    0                           1                    1   
4381                    0                           1                    0   
3862                    0                           0                    0   
43                      1                           1                    0   

      ...  location_Kalena Agrahara  location_Horamavu Agara  \
2078  ...                         0                        0   
6855  ...                         0                        0   
4381  ...                         0                        0   
3862  ...                         0                        0   
43    ...                         0                        0   

      location_Vidyaranyapura  location_BTM 2nd Stage  \
2078                        0                       0   
6855                        0                       0   
4381                        0                       0   
3862                        0                       0   
43                          0                       0   

      location_Hebbal Kempapura  location_Hosur Road  \
2078                          0                    0   
6855                          0                    0   
4381                          0                    0   
3862                          0                    0   
43                            0                    0   

      location_Horamavu Banaswadi  location_Domlur  location_Mahadevpura  \
2078                            0                0                     0   
6855                            0                0                     0   
4381                            0                0                     0   
3862                            0                0                     0   
43                              0                0                     0   

      location_Tumkur Road  
2078                     0  
6855                     0  
4381                     0  
3862                     0  
43                       0  

[5 rows x 107 columns]

In [49]:
X_test.iloc[-2,:]

bath                              2.000000
balcony                           1.000000
total_sqft_int                 1167.000000
bhk                               2.000000
price_per_sqft                 5398.457584
                                  ...     
location_Hosur Road               0.000000
location_Horamavu Banaswadi       0.000000
location_Domlur                   0.000000
location_Mahadevpura              0.000000
location_Tumkur Road              0.000000
Name: 3862, Length: 107, dtype: float64

In [51]:
regressor.predict([X_test.iloc[-2,:]])

array([63.])

In [52]:
y_test.iloc[-2]

63.0

In [54]:
y_pred = regressor.predict(X_test)

In [55]:
y_pred

array([ 77.378,  39.808, 120.2  , ...,  33.405,  63.   , 184.4  ])

In [57]:
y_test

2435     80.00
3113     40.00
426     120.00
1124     79.00
1161     45.00
         ...  
2078     28.34
6855     84.00
4381     32.00
3862     63.00
43      180.00
Name: price, Length: 1424, dtype: float64

In [64]:
X_test.iloc[-3,:]

bath                              1.000000
balcony                           2.000000
total_sqft_int                  665.000000
bhk                               1.000000
price_per_sqft                 4812.030075
                                  ...     
location_Hosur Road               0.000000
location_Horamavu Banaswadi       0.000000
location_Domlur                   0.000000
location_Mahadevpura              0.000000
location_Tumkur Road              0.000000
Name: 4381, Length: 107, dtype: float64

In [65]:
regressor.predict([X_test.iloc[-3,:]])

array([33.405])

In [66]:
y_test.tail

<bound method NDFrame.tail of 2435     80.00
3113     40.00
426     120.00
1124     79.00
1161     45.00
         ...  
2078     28.34
6855     84.00
4381     32.00
3862     63.00
43      180.00
Name: price, Length: 1424, dtype: float64>

In [67]:
y_pred = regressor.predict(X_test[0:20])

In [68]:
y_pred

array([ 77.378,  39.808, 120.2  ,  78.6  ,  47.38 ,  38.998,  52.48 ,
        78.   , 100.036,  62.18 , 104.   , 241.   , 238.6  , 244.6  ,
       159.6  ,  48.2  ,  86.2  ,  94.038, 160.   ,  53.8  ])

In [70]:
y_test.head(20)

2435     80.0
3113     40.0
426     120.0
1124     79.0
1161     45.0
1724     39.0
1110     53.0
3591     78.0
1978    101.0
4383     62.0
4602    105.0
3536    246.0
820     198.0
4500    233.0
5550    145.0
1273     48.0
1905     86.0
5007     94.0
4447    160.0
6589     54.0
Name: price, dtype: float64